spring:
  application:
    name: security-learning-01
  datasource:
    url: jdbc:postgresql://postgres:5432/shayan
    username: shayan
    password: shayan
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      '[hibernate.dialect]': org.hibernate.dialect.PostgreSQLDialect
      '[hibernate.format_sql]': true
server:
  port: 8080
